export const CHECK_HELP_REQUEST = 'CHECK_HELP_REQUEST';
export const CHECK_HELP_SUCCESS = 'CHECK_HELP_SUCCESS';
export const CHECK_HELP_ERROR = 'CHECK_HELP_ERROR';

export const METHOD_HELP_REQUEST = 'METHOD_HELP_REQUEST';
export const METHOD_HELP_SUCCESS = 'METHOD_HELP_SUCCESS';
export const METHOD_HELP_ERROR = 'METHOD_HELP_ERROR';

export const TEST_REQUEST_REQUEST = 'TEST_REQUEST_REQUEST';
export const TEST_REQUEST_SUCCESS = 'TEST_REQUEST_SUCCESS';
export const TEST_REQUEST_ERROR = 'TEST_REQUEST_ERROR';

